name: flutter_jigsaw_puzzle
description: A simple Jigsaw Puzzle lib built with Flutter that supports custom grids of varying sizes.
version: 0.2.2
homepage: https://github.com/o-compilador/flutter_jigsaw_puzzle

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  flutter: { sdk: flutter }
  image: ^3.2.2